# Generated by Django 6.0.5 on 2026-05-20 17:20

import apps.cadastros.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pregao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=30, verbose_name="Número do Pregão"),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "nome_pregoeiro",
                    models.CharField(max_length=255, verbose_name="Nome do Pregoeiro"),
                ),
                (
                    "cpf_pregoeiro",
                    models.CharField(
                        max_length=14,
                        validators=[apps.cadastros.models.validar_cpf],
                        verbose_name="CPF do Pregoeiro",
                    ),
                ),
                (
                    "local_pregao",
                    models.CharField(max_length=255, verbose_name="Local do Pregão"),
                ),
                ("data_pregao", models.DateField(verbose_name="Data do Pregão")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nao_iniciado", "Não iniciado"),
                            ("em_andamento", "Em andamento"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="nao_iniciado",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "finalizado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizado em"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pregoes_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregão",
                "verbose_name_plural": "Pregões",
                "ordering": ["-ano", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="PregaoFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordem_inicial",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ordem inicial"
                    ),
                ),
                (
                    "ativo_no_pregao",
                    models.BooleanField(default=True, verbose_name="Ativo no pregão"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pregoes.pregao",
                        verbose_name="Pregão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedor do Pregão",
                "verbose_name_plural": "Fornecedores do Pregão",
                "ordering": ["ordem_inicial", "fornecedor__razao_social"],
            },
        ),
        migrations.AddField(
            model_name="pregao",
            name="fornecedores",
            field=models.ManyToManyField(
                related_name="pregoes",
                through="pregoes.PregaoFornecedor",
                to="cadastros.fornecedor",
                verbose_name="Fornecedores",
            ),
        ),
        migrations.CreateModel(
            name="PregaoMunicipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.municipio",
                        verbose_name="Município",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pregoes.pregao",
                        verbose_name="Pregão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Município do Pregão",
                "verbose_name_plural": "Municípios do Pregão",
            },
        ),
        migrations.AddField(
            model_name="pregao",
            name="municipios",
            field=models.ManyToManyField(
                related_name="pregoes",
                through="pregoes.PregaoMunicipio",
                to="cadastros.municipio",
                verbose_name="Municípios",
            ),
        ),
        migrations.CreateModel(
            name="QuantitativoEscola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quantitativos",
                        to="cadastros.escola",
                        verbose_name="Escola",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quantitativos_escola",
                        to="cadastros.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantitativos_escola",
                        to="pregoes.pregao",
                        verbose_name="Pregão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quantitativo por Escola",
                "verbose_name_plural": "Quantitativos por Escola",
                "ordering": ["escola__nome_escola", "item__nome_item"],
            },
        ),
        migrations.CreateModel(
            name="QuantitativoPregao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quantitativos_pregao",
                        to="cadastros.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantitativos_pregao",
                        to="pregoes.pregao",
                        verbose_name="Pregão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quantitativo por Pregão",
                "verbose_name_plural": "Quantitativos por Pregão",
                "ordering": ["item__nome_item"],
            },
        ),
        migrations.AddConstraint(
            model_name="pregaofornecedor",
            constraint=models.UniqueConstraint(
                fields=("pregao", "fornecedor"), name="unique_fornecedor_por_pregao"
            ),
        ),
        migrations.AddConstraint(
            model_name="pregaomunicipio",
            constraint=models.UniqueConstraint(
                fields=("pregao", "municipio"), name="unique_municipio_por_pregao"
            ),
        ),
        migrations.AddConstraint(
            model_name="pregao",
            constraint=models.UniqueConstraint(
                fields=("numero", "ano"), name="unique_numero_ano_pregao"
            ),
        ),
        migrations.AddConstraint(
            model_name="quantitativoescola",
            constraint=models.UniqueConstraint(
                fields=("pregao", "escola", "item"),
                name="unique_item_por_escola_pregao",
            ),
        ),
        migrations.AddConstraint(
            model_name="quantitativopregao",
            constraint=models.UniqueConstraint(
                fields=("pregao", "item"), name="unique_item_por_pregao_quantitativo"
            ),
        ),
    ]
