# Generated by Django 6.0.5 on 2026-05-20 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
        ("pregoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PregaoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(verbose_name="Ordem")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_disputa", "Em disputa"),
                            ("encerrado", "Encerrado"),
                            ("deserto", "Deserto"),
                            ("fracassado", "Fracassado"),
                        ],
                        default="pendente",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "quantidade_total",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Quantidade Total"
                    ),
                ),
                (
                    "menor_lance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Menor Lance",
                    ),
                ),
                (
                    "iniciado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "encerrado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Encerrado em"
                    ),
                ),
                (
                    "fornecedor_vencedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_vencidos",
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor Vencedor",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execucoes",
                        to="cadastros.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_execucao",
                        to="pregoes.pregao",
                        verbose_name="Pregão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pregão",
                "verbose_name_plural": "Itens do Pregão",
                "ordering": ["pregao", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="Lance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_lance",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.0001)],
                        verbose_name="Valor do Lance",
                    ),
                ),
                (
                    "ordem_lance",
                    models.PositiveIntegerField(verbose_name="Ordem do Lance"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lances",
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lances",
                        to="pregoes.pregao",
                        verbose_name="Pregão",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lances_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "pregao_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lances",
                        to="pregoes.pregaoitem",
                        verbose_name="Item do Pregão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lance",
                "verbose_name_plural": "Lances",
                "ordering": ["pregao_item", "ordem_lance"],
            },
        ),
        migrations.CreateModel(
            name="DesistenciaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="desistencias",
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desistencias",
                        to="pregoes.pregao",
                        verbose_name="Pregão",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="desistencias_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "pregao_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desistencias",
                        to="pregoes.pregaoitem",
                        verbose_name="Item do Pregão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Desistência do Item",
                "verbose_name_plural": "Desistências dos Itens",
            },
        ),
        migrations.CreateModel(
            name="ResultadoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_resultado",
                    models.CharField(
                        choices=[
                            ("adjudicado", "Adjudicado"),
                            ("deserto", "Deserto"),
                            ("fracassado", "Fracassado"),
                        ],
                        max_length=30,
                        verbose_name="Status do Resultado",
                    ),
                ),
                (
                    "primeiro_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor do 1º Colocado",
                    ),
                ),
                (
                    "segundo_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor do 2º Colocado",
                    ),
                ),
                (
                    "terceiro_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor do 3º Colocado",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="pregoes.pregao",
                        verbose_name="Pregão",
                    ),
                ),
                (
                    "pregao_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultado",
                        to="pregoes.pregaoitem",
                        verbose_name="Item do Pregão",
                    ),
                ),
                (
                    "primeiro_fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_primeiro_lugar",
                        to="cadastros.fornecedor",
                        verbose_name="1º Colocado",
                    ),
                ),
                (
                    "segundo_fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_segundo_lugar",
                        to="cadastros.fornecedor",
                        verbose_name="2º Colocado",
                    ),
                ),
                (
                    "terceiro_fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_terceiro_lugar",
                        to="cadastros.fornecedor",
                        verbose_name="3º Colocado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado do Item",
                "verbose_name_plural": "Resultados dos Itens",
                "ordering": ["pregao", "pregao_item__ordem"],
            },
        ),
        migrations.AddConstraint(
            model_name="pregaoitem",
            constraint=models.UniqueConstraint(
                fields=("pregao", "item"), name="unique_item_execucao_por_pregao"
            ),
        ),
        migrations.AddConstraint(
            model_name="pregaoitem",
            constraint=models.UniqueConstraint(
                fields=("pregao", "ordem"), name="unique_ordem_item_por_pregao"
            ),
        ),
        migrations.AddConstraint(
            model_name="lance",
            constraint=models.UniqueConstraint(
                fields=("pregao_item", "ordem_lance"),
                name="unique_ordem_lance_por_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="desistenciaitem",
            constraint=models.UniqueConstraint(
                fields=("pregao_item", "fornecedor"),
                name="unique_desistencia_fornecedor_item",
            ),
        ),
    ]
