# Generated by Django 6.0.5 on 2026-05-21 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
        ("pregoes", "0002_pregaoitem_lance_desistenciaitem_resultadoitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pregaoitem",
            name="fornecedor_atual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_em_rodada",
                to="cadastros.fornecedor",
                verbose_name="Fornecedor Atual",
            ),
        ),
        migrations.AddField(
            model_name="pregaoitem",
            name="rodada_atual",
            field=models.PositiveIntegerField(default=1, verbose_name="Rodada Atual"),
        ),
    ]
