# Generated by Django 6.0.5 on 2026-05-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
        ("pregoes", "0003_pregaoitem_fornecedor_atual_pregaoitem_rodada_atual"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropostaInicialItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marca",
                    models.CharField(blank=True, max_length=150, verbose_name="Marca"),
                ),
                (
                    "preco_inicial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Preço Inicial",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="propostas_iniciais",
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propostas_iniciais",
                        to="pregoes.pregao",
                        verbose_name="Pregão",
                    ),
                ),
                (
                    "pregao_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propostas_iniciais",
                        to="pregoes.pregaoitem",
                        verbose_name="Item do Pregão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposta Inicial do Item",
                "verbose_name_plural": "Propostas Iniciais dos Itens",
                "ordering": ["pregao_item__ordem", "fornecedor__razao_social"],
                "unique_together": {("pregao", "pregao_item", "fornecedor")},
            },
        ),
    ]
