# Generated by Django 6.0.5 on 2026-05-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pregoes", "0004_propostainicialitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="propostainicialitem",
            name="participa",
            field=models.BooleanField(
                default=True,
                help_text="Desmarque quando o fornecedor não participar deste item.",
                verbose_name="Participa do item",
            ),
        ),
    ]
