# Generated by Django 6.0.5 on 2026-06-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pregoes", "0005_propostainicialitem_participa"),
    ]

    operations = [
        migrations.AddField(
            model_name="pregaoitem",
            name="media_preco",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Preço médio/de referência do item neste pregão.",
                max_digits=12,
                null=True,
                verbose_name="Média de Preço",
            ),
        ),
        migrations.AddField(
            model_name="pregaoitem",
            name="percentual_alerta_media",
            field=models.DecimalField(
                decimal_places=2,
                default=25,
                help_text="Percentual permitido para diferença em relação à média cadastrada.",
                max_digits=5,
                verbose_name="Percentual de Alerta da Média",
            ),
        ),
    ]
