# Generated by Django 6.0.5 on 2026-07-27 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_unidademedida_alter_item_unidade_medida"),
        ("pregoes", "0006_pregaoitem_media_preco_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pregao",
            options={
                "ordering": ["-ano", "-numero"],
                "verbose_name": "Certame",
                "verbose_name_plural": "Certames",
            },
        ),
        migrations.RemoveConstraint(
            model_name="pregao",
            name="unique_numero_ano_pregao",
        ),
        migrations.AddField(
            model_name="pregao",
            name="tipo_certame",
            field=models.CharField(
                choices=[
                    ("pregao_presencial", "Pregão Presencial"),
                    ("chamada_publica", "Chamada Pública"),
                ],
                default="pregao_presencial",
                help_text="Define se o processo será executado como Pregão Presencial ou Chamada Pública.",
                max_length=30,
                verbose_name="Tipo de Certame",
            ),
        ),
        migrations.AlterField(
            model_name="pregao",
            name="numero",
            field=models.CharField(max_length=30, verbose_name="Número do Certame"),
        ),
        migrations.AddConstraint(
            model_name="pregao",
            constraint=models.UniqueConstraint(
                fields=("tipo_certame", "numero", "ano"),
                name="unique_tipo_numero_ano_certame",
            ),
        ),
    ]
