# Generated by Django 6.0.5 on 2026-08-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pregoes", "0007_alter_pregao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pregao",
            name="percentual_alerta_media",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                help_text="Percentual de alerta aplicado a todos os itens deste certame.",
                max_digits=5,
                verbose_name="Percentual de Alerta da Média",
            ),
        ),
        migrations.AlterField(
            model_name="pregaoitem",
            name="percentual_alerta_media",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                help_text="Campo legado. O percentual vigente é definido no certame.",
                max_digits=5,
                verbose_name="Percentual de Alerta da Média (legado)",
            ),
        ),
    ]
