# Generated by Django 6.0.5 on 2026-08-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pregoes", "0008_pregao_percentual_alerta_media_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pregao",
            name="numero_processo",
            field=models.CharField(
                blank=True,
                help_text="Número do processo administrativo vinculado ao certame.",
                max_length=100,
                verbose_name="Número do Processo",
            ),
        ),
    ]
