from django.urls import path
from . import views

app_name = "documentos"

urlpatterns = [
    path(
        "relatorios/resumo-financeiro-certame/",
        views.relatorios_resumo_financeiro_certame,
        name="relatorios_resumo_financeiro_certame",
    ),
    path(
        "relatorios/resumo-financeiro-escola/",
        views.relatorios_resumo_financeiro_escola,
        name="relatorios_resumo_financeiro_escola",
    ),
    path(
        "relatorios/distratos/",
        views.relatorios_distratos,
        name="relatorios_distratos",
    ),
    path(
        "relatorios/realinhamentos/",
        views.relatorios_realinhamentos,
        name="relatorios_realinhamentos",
    ),
    path(
        "relatorios/consolidado-chamada-publica/",
        views.relatorios_consolidado_chamada_publica,
        name="relatorios_consolidado_chamada_publica",
    ),
    path(
        "relatorios/ajax/escolas-contratos-por-certame/<int:pregao_id>/",
        views.relatorios_escolas_contratos_por_certame,
        name="relatorios_escolas_contratos_por_certame",
    ),
    path(
        "relatorios/ajax/fornecedores-contratos-por-certame/<int:pregao_id>/",
        views.relatorios_fornecedores_contratos_por_certame,
        name="relatorios_fornecedores_contratos_por_certame",
    ),
    path(
        "relatorios/contratos-por-escola/",
        views.relatorios_contratos_por_escola,
        name="relatorios_contratos_por_escola",
    ),
    path(
        "relatorios/contratos-por-fornecedor/",
        views.relatorios_contratos_por_fornecedor,
        name="relatorios_contratos_por_fornecedor",
    ),
    path(
        "relatorios/itens-sem-contrato/",
        views.relatorios_itens_sem_contrato,
        name="relatorios_itens_sem_contrato",
    ),
    path(
        "relatorios/calendario-certames/",
        views.relatorios_calendario_certames,
        name="relatorios_calendario_certames",
    ),
    path(
        "relatorios/quantitativo-certame/",
        views.relatorios_quantitativo_certame,
        name="relatorios_quantitativo_certame",
    ),
    path(
        "relatorios/quantitativo-escola/",
        views.relatorios_quantitativo_escola,
        name="relatorios_quantitativo_escola",
    ),
    path(
        "relatorios/saldo-certame/",
        views.relatorios_saldo_certame,
        name="relatorios_saldo_certame",
    ),
    path(
        "relatorios/saldo-escola/",
        views.relatorios_saldo_escola,
        name="relatorios_saldo_escola",
    ),
    path(
        "relatorios/ajax/escolas-por-certame/<int:pregao_id>/",
        views.relatorios_escolas_por_certame,
        name="relatorios_escolas_por_certame",
    ),
    path(
        "chamada-publica/contratos/",
        views.contratos_chamada_publica,
        name="contratos_chamada_publica",
    ),
    path(
        "chamada-publica/contratos/<int:pregao_id>/",
        views.contratos_chamada_publica_pregao,
        name="contratos_chamada_publica_pregao",
    ),
    path(
        "chamada-publica/resultado/<int:pregao_id>/word/",
        views.gerar_resultado_chamada_publica_word,
        name="gerar_resultado_chamada_publica_word",
    ),
    path(
        "chamada-publica/resultado/<int:pregao_id>/pdf/",
        views.gerar_resultado_chamada_publica_pdf,
        name="gerar_resultado_chamada_publica_pdf",
    ),
    path(
        "chamada-publica/adjudicacao/",
        views.adjudicacao_chamada_publica,
        name="adjudicacao_chamada_publica",
    ),
    path(
        "chamada-publica/resultado/",
        views.resultado_chamada_publica,
        name="resultado_chamada_publica",
    ),
    path(
        "chamada-publica/projetos-venda/",
        views.projetos_venda,
        name="projetos_venda",
    ),
    path(
        "chamada-publica/projetos-venda/<int:pregao_id>/registrar/",
        views.registrar_projeto_venda,
        name="registrar_projeto_venda",
    ),
    path(
        "chamada-publica/projetos-venda/<int:projeto_id>/editar/",
        views.editar_projeto_venda,
        name="editar_projeto_venda",
    ),
    path(
        "chamada-publica/projetos-venda/<int:projeto_id>/cancelar/",
        views.cancelar_projeto_venda,
        name="cancelar_projeto_venda",
    ),
    path(
        "pregoes-finalizados/",
        views.pregoes_finalizados,
        name="pregoes_finalizados",
    ),
    path(
        "pregoes-finalizados/<int:pregao_id>/planilha-lances/",
        views.planilha_lances,
        name="planilha_lances",
    ),
    path(
        "pregoes-finalizados/<int:pregao_id>/fornecedores-vencedores/",
        views.fornecedores_vencedores,
        name="fornecedores_vencedores",
    ),
    path(
        "pregoes-finalizados/<int:pregao_id>/resultado-final/",
        views.resultado_final,
        name="resultado_final",
    ),
    path(
        "pregoes-finalizados/<int:pregao_id>/contratos/",
        views.contratos_pregao,
        name="contratos_pregao",
    ),
    path(
        "pregoes-finalizados/<int:pregao_id>/contratos/lote/",
        views.contratos_lote,
        name="contratos_lote",
    ),
    path(
        "pregoes-finalizados/<int:pregao_id>/contratos/<int:escola_id>/<int:fornecedor_id>/previa/",
        views.previa_contrato,
        name="previa_contrato",
    ),
    path(
        "pregoes-finalizados/<int:pregao_id>/contratos/<int:escola_id>/<int:fornecedor_id>/registrar/",
        views.registrar_contrato,
        name="registrar_contrato",
    ),
    path(
        "contratos/<int:contrato_id>/visualizar/",
        views.visualizar_contrato,
        name="visualizar_contrato",
    ),
    path(
    "contratos/<int:contrato_id>/word/",
    views.gerar_contrato_word,
    name="gerar_contrato_word",
    ),
    path(
    "contratos/<int:contrato_id>/pdf/",
    views.gerar_contrato_pdf,
    name="gerar_contrato_pdf",
    ),
    path(
    "contratos-gerados/",
    views.contratos_gerados,
    name="contratos_gerados",
    ),
    path(
        "contratos-gerados/lote/<str:formato>/download/",
        views.baixar_contratos_lote,
        name="baixar_contratos_lote",
    ),
    path(
    "contratos/<int:contrato_id>/cancelar/",
    views.cancelar_contrato,
    name="cancelar_contrato",
    ),
    path(
        "contratos/<int:contrato_id>/distrato/",
        views.registrar_distrato_contrato,
        name="registrar_distrato_contrato",
    ),
    path(
        "contratos/<int:contrato_id>/termo-rescisao-word/",
        views.gerar_termo_rescisao_word,
        name="gerar_termo_rescisao_word",
    ),
    path(
        "contratos/<int:contrato_id>/termo-rescisao-pdf/",
        views.gerar_termo_rescisao_pdf,
        name="gerar_termo_rescisao_pdf",
    ),
    path(
        "realinhamento-precos/",
        views.realinhamento_precos,
        name="realinhamento_precos",
    ),
    path(
        "realinhamentos/<int:realinhamento_id>/termo-aditivo/",
        views.registrar_termo_aditivo,
        name="registrar_termo_aditivo",
    ),
    path(
        "realinhamentos/<int:realinhamento_id>/termo-aditivo-word/",
        views.gerar_termo_aditivo_word,
        name="gerar_termo_aditivo_word",
    ),
    path(
        "realinhamentos/<int:realinhamento_id>/termo-aditivo-pdf/",
        views.gerar_termo_aditivo_pdf,
        name="gerar_termo_aditivo_pdf",
    ),

    path(
        "realinhamentos/<int:realinhamento_id>/documentos/<str:tipo_documento>/<str:formato>/",
        views.gerar_documento_realinhamento,
        name="gerar_documento_realinhamento",
    ),
    path(
        "troca-marca/",
        views.troca_marca,
        name="troca_marca",
    ),
    path(
        "troca-marca/<int:troca_id>/termo-aditivo/",
        views.registrar_termo_aditivo_marca,
        name="registrar_termo_aditivo_marca",
    ),
    path(
        "troca-marca/<int:troca_id>/termo-aditivo-word/",
        views.gerar_termo_aditivo_marca_word,
        name="gerar_termo_aditivo_marca_word",
    ),
    path(
        "troca-marca/<int:troca_id>/termo-aditivo-pdf/",
        views.gerar_termo_aditivo_marca_pdf,
        name="gerar_termo_aditivo_marca_pdf",
    ),
    path(
    "ajax/escolas-por-pregao/<int:pregao_id>/",
    views.documentos_escolas_por_pregao,
    name="documentos_escolas_por_pregao",
    ),
    path(
        "ajax/fornecedores-por-pregao/<int:pregao_id>/",
        views.documentos_fornecedores_por_pregao,
        name="documentos_fornecedores_por_pregao",
    ),
    path(
        "ajax/contratos-por-filtros/",
        views.documentos_contratos_por_filtros,
        name="documentos_contratos_por_filtros",
    ),
]