# Generated by Django 6.0.5 on 2026-08-03 20:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0004_alter_escola_cnpj_alter_fornecedor_cnpj"),
        ("documentos", "0010_projetovendaitem_marca"),
        ("pregoes", "0007_alter_pregao_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AquisicaoNotaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo_entrada",
                    models.CharField(
                        choices=[
                            ("xml", "Upload do XML da NF-e"),
                            (
                                "tabela_colada",
                                "Colar tabela da aba Produtos e Serviços",
                            ),
                            ("manual", "Digitação manual dos itens"),
                        ],
                        default="xml",
                        max_length=30,
                        verbose_name="Forma de Entrada dos Itens",
                    ),
                ),
                (
                    "chave_acesso",
                    models.CharField(
                        blank=True,
                        help_text="Informe os 44 dígitos da chave de acesso da NF-e.",
                        max_length=44,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="A chave de acesso da NF-e deve conter exatamente 44 dígitos numéricos.",
                                regex="^\\d{44}$",
                            )
                        ],
                        verbose_name="Chave de Acesso da NF-e",
                    ),
                ),
                (
                    "numero_nota",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Número da Nota Fiscal"
                    ),
                ),
                (
                    "serie",
                    models.CharField(blank=True, max_length=10, verbose_name="Série"),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Data de Recebimento",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Valor Total da Nota",
                    ),
                ),
                (
                    "arquivo_xml",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="aquisicoes/xml/",
                        verbose_name="Arquivo XML da NF-e",
                    ),
                ),
                (
                    "tabela_colada",
                    models.TextField(
                        blank=True,
                        help_text="Campo reservado para a etapa de processamento da tabela colada.",
                        verbose_name="Tabela copiada da aba Produtos e Serviços",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("em_conferencia", "Em conferência"),
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="rascunho",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "confirmado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmado em"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquisicoes_notas_fiscais_confirmadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmado por",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contrato relacionado à aquisição. Pode ser definido automaticamente nas próximas etapas.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquisicoes_notas_fiscais",
                        to="documentos.contratogerado",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquisicoes_notas_fiscais_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquisicoes_notas_fiscais",
                        to="cadastros.escola",
                        verbose_name="Escola",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquisicoes_notas_fiscais",
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquisicoes_notas_fiscais",
                        to="pregoes.pregao",
                        verbose_name="Certame",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aquisição por Nota Fiscal",
                "verbose_name_plural": "Aquisições por Notas Fiscais",
                "ordering": ["-data_recebimento", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="AquisicaoNotaFiscalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_produto",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Código do Produto na NF-e",
                    ),
                ),
                (
                    "descricao_produto",
                    models.CharField(
                        max_length=500, verbose_name="Descrição do Produto na NF-e"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(blank=True, max_length=40, verbose_name="Unidade"),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Valor Unitário",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente de vínculo"),
                            ("vinculado", "Vinculado ao contrato"),
                            ("divergente", "Com divergência"),
                        ],
                        default="pendente",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "conferido",
                    models.BooleanField(default=False, verbose_name="Conferido"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "contrato_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquisicoes_itens",
                        to="documentos.contratoitemgerado",
                        verbose_name="Item do Contrato",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquisicoes_notas_fiscais",
                        to="cadastros.item",
                        verbose_name="Item Cadastrado",
                    ),
                ),
                (
                    "nota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="aquisicoes.aquisicaonotafiscal",
                        verbose_name="Nota Fiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Aquisição por NF-e",
                "verbose_name_plural": "Itens da Aquisição por NF-e",
                "ordering": ["descricao_produto"],
            },
        ),
        migrations.CreateModel(
            name="ProdutoNotaFiscalMapeamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao_nota",
                    models.CharField(
                        max_length=500, verbose_name="Descrição do Produto na NF-e"
                    ),
                ),
                (
                    "unidade_nota",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Unidade na NF-e"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapeamentos_produtos_nfe",
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapeamentos_produtos_nfe",
                        to="cadastros.item",
                        verbose_name="Item Cadastrado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeamento de Produto da NF-e",
                "verbose_name_plural": "Mapeamentos de Produtos da NF-e",
                "ordering": ["fornecedor__razao_social", "descricao_nota"],
            },
        ),
        migrations.AddConstraint(
            model_name="aquisicaonotafiscal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chave_acesso", ""), _negated=True),
                fields=("chave_acesso",),
                name="aquisicao_nfe_chave_acesso_unica_quando_informada",
            ),
        ),
        migrations.AddConstraint(
            model_name="produtonotafiscalmapeamento",
            constraint=models.UniqueConstraint(
                fields=("fornecedor", "descricao_nota", "unidade_nota"),
                name="produto_nfe_mapeamento_unico_por_fornecedor",
            ),
        ),
    ]
