# Generated by Django 6.0.5 on 2026-08-26 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0007_fornecedor_fornecedor_me_epp"),
        ("pregoes", "0009_pregao_numero_processo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficioMEEPP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordem_convocacao",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Ordem de Convocação"
                    ),
                ),
                (
                    "valor_referencia",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Melhor Valor de Referência",
                    ),
                ),
                (
                    "valor_original_me_epp",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Valor Original da ME/EPP",
                    ),
                ),
                (
                    "percentual_margem",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=5,
                        verbose_name="Percentual da Margem",
                    ),
                ),
                (
                    "nova_oferta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Nova Oferta da ME/EPP",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("exercido", "Exercido"),
                            ("recusado", "Não exercido"),
                            ("encerrado", "Encerrado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficios_me_epp",
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor ME/EPP",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficios_me_epp",
                        to="pregoes.pregao",
                        verbose_name="Pregão",
                    ),
                ),
                (
                    "pregao_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficios_me_epp",
                        to="pregoes.pregaoitem",
                        verbose_name="Item do Pregão",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficios_me_epp_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefício ME/EPP",
                "verbose_name_plural": "Benefícios ME/EPP",
                "ordering": ["pregao_item", "ordem_convocacao", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pregao_item", "fornecedor"),
                        name="unique_beneficio_me_epp_item_fornecedor",
                    )
                ],
            },
        ),
    ]
