# Generated by Django 6.0.5 on 2026-06-10 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0002_unidademedida_alter_item_unidade_medida"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("administrador", "Administrador"),
                            ("pregoeiro", "Pregoeiro"),
                            ("consulta_escola", "Consulta/Escola"),
                        ],
                        default="consulta_escola",
                        max_length=30,
                        verbose_name="Perfil",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        blank=True,
                        help_text="Use principalmente para usuários do perfil Consulta/Escola.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios_consulta",
                        to="cadastros.escola",
                        verbose_name="Escola vinculada",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_acesso",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
                "ordering": ["usuario__first_name", "usuario__username"],
            },
        ),
    ]
