# Generated by Django 6.0.5 on 2026-05-20 14:40

import apps.cadastros.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "razao_social",
                    models.CharField(max_length=255, verbose_name="Razão Social"),
                ),
                (
                    "cnpj",
                    models.CharField(
                        max_length=18,
                        unique=True,
                        validators=[apps.cadastros.models.validar_cnpj],
                        verbose_name="CNPJ",
                    ),
                ),
                ("endereco", models.CharField(max_length=255, verbose_name="Endereço")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Telefone"
                    ),
                ),
                (
                    "representante_legal",
                    models.CharField(
                        max_length=255, verbose_name="Representante Legal"
                    ),
                ),
                (
                    "rg_representante",
                    models.CharField(max_length=50, verbose_name="RG do Representante"),
                ),
                (
                    "orgao_expedidor_representante",
                    models.CharField(max_length=50, verbose_name="Órgão Expedidor"),
                ),
                (
                    "cpf_representante",
                    models.CharField(
                        max_length=14,
                        validators=[apps.cadastros.models.validar_cpf],
                        verbose_name="CPF do Representante",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, verbose_name="E-mail"
                    ),
                ),
                (
                    "nome_banco",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nome do Banco"
                    ),
                ),
                (
                    "agencia",
                    models.CharField(blank=True, max_length=30, verbose_name="Agência"),
                ),
                (
                    "conta_corrente",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Conta Corrente"
                    ),
                ),
                (
                    "pix",
                    models.CharField(blank=True, max_length=150, verbose_name="PIX"),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "ordering": ["razao_social"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "nome_item",
                    models.CharField(max_length=255, verbose_name="Nome do Item"),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[
                            ("kg", "Quilograma"),
                            ("litro", "Litro"),
                            ("unidade", "Unidade"),
                            ("pacote", "Pacote"),
                            ("caixa", "Caixa"),
                            ("duzia", "Dúzia"),
                        ],
                        max_length=30,
                        verbose_name="Unidade de Medida",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Item")),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Itens",
                "ordering": ["nome_item"],
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=120)),
                ("uf", models.CharField(default="MT", max_length=2)),
            ],
            options={
                "verbose_name": "Município",
                "verbose_name_plural": "Municípios",
                "ordering": ["nome"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nome", "uf"), name="unique_municipio_uf"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Escola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "nome_escola",
                    models.CharField(max_length=255, verbose_name="Nome da Escola"),
                ),
                (
                    "cnpj",
                    models.CharField(
                        max_length=18,
                        unique=True,
                        validators=[apps.cadastros.models.validar_cnpj],
                        verbose_name="CNPJ",
                    ),
                ),
                ("endereco", models.CharField(max_length=255, verbose_name="Endereço")),
                (
                    "numero",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "presidente_cdce",
                    models.CharField(max_length=255, verbose_name="Presidente do CDCE"),
                ),
                (
                    "rg_presidente",
                    models.CharField(max_length=50, verbose_name="RG do Presidente"),
                ),
                (
                    "cpf_presidente",
                    models.CharField(
                        max_length=14,
                        validators=[apps.cadastros.models.validar_cpf],
                        verbose_name="CPF do Presidente",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escolas",
                        to="cadastros.municipio",
                        verbose_name="Município",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escola",
                "verbose_name_plural": "Escolas",
                "ordering": ["nome_escola"],
            },
        ),
    ]
