# Generated by Django 6.0.5 on 2026-05-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "sigla",
                    models.CharField(blank=True, max_length=20, verbose_name="Sigla"),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código usado internamente nos itens. Ex.: kg, litro, unidade.",
                        max_length=50,
                        unique=True,
                        verbose_name="Código interno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "ordering": ["nome"],
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="unidade_medida",
            field=models.CharField(max_length=50, verbose_name="Unidade de Medida"),
        ),
    ]
