# Generated by Django 6.0.5 on 2026-07-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_unidademedida_alter_item_unidade_medida"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="caf_dap",
            field=models.CharField(
                blank=True,
                help_text="Número do CAF ou DAP do fornecedor individual ou do grupo formal/cooperativa.",
                max_length=50,
                verbose_name="CAF/DAP",
            ),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="cpf_fornecedor_individual",
            field=models.CharField(
                blank=True,
                help_text="Use este campo quando o fornecedor for pessoa física da agricultura familiar.",
                max_length=14,
                verbose_name="CPF do Fornecedor Individual",
            ),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="quantidade_caf_dap",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Para grupo formal/cooperativa, informe a quantidade de CAF/DAP vinculadas.",
                verbose_name="Quantidade de CAF/DAP",
            ),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="tipo_fornecedor_chamada",
            field=models.CharField(
                choices=[
                    ("empresa_comum", "Empresa comum"),
                    ("individual", "Fornecedor Individual"),
                    ("grupo_formal", "Grupo Formal / Cooperativa"),
                ],
                default="empresa_comum",
                help_text="Classificação usada especialmente na Chamada Pública da Agricultura Familiar.",
                max_length=30,
                verbose_name="Tipo do Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="razao_social",
            field=models.CharField(
                max_length=255, verbose_name="Razão Social / Nome do Fornecedor"
            ),
        ),
    ]
