# Generated by Django 6.0.5 on 2026-07-28 19:38

import apps.cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_fornecedor_caf_dap_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escola",
            name="cnpj",
            field=models.CharField(
                blank=True,
                help_text="Obrigatório para empresa comum e grupo formal/cooperativa. Não usado para fornecedor individual.",
                max_length=18,
                null=True,
                unique=True,
                validators=[apps.cadastros.models.validar_cnpj],
                verbose_name="CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="cnpj",
            field=models.CharField(
                blank=True,
                help_text="Obrigatório para empresa comum e grupo formal/cooperativa. Não usado para fornecedor individual.",
                max_length=18,
                null=True,
                unique=True,
                validators=[apps.cadastros.models.validar_cnpj],
                verbose_name="CNPJ",
            ),
        ),
    ]
