# Generated by Django 6.0.5 on 2026-08-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_alter_escola_cnpj_alter_fornecedor_cnpj"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="caf_dap_juridica",
            field=models.CharField(
                blank=True,
                help_text="Obrigatória para grupo formal/cooperativa.",
                max_length=50,
                verbose_name="CAF/DAP Jurídica",
            ),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="procurador",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Procurador"
            ),
        ),
    ]
