# Generated by Django 6.0.5 on 2026-08-25 14:45

import apps.cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_fornecedor_caf_dap_juridica_fornecedor_procurador"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="cpf_procurador",
            field=models.CharField(
                blank=True,
                max_length=14,
                validators=[apps.cadastros.models.validar_cpf],
                verbose_name="CPF do Procurador",
            ),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="orgao_expedidor_procurador",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Órgão Expedidor do Procurador"
            ),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="rg_procurador",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="RG do Procurador"
            ),
        ),
    ]
