# Generated by Django 6.0.5 on 2026-08-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0006_fornecedor_cpf_procurador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="fornecedor_me_epp",
            field=models.BooleanField(
                default=False,
                help_text="Marque quando o fornecedor for Microempresa (ME) ou Empresa de Pequeno Porte (EPP).",
                verbose_name="Fornecedor ME/EPP",
            ),
        ),
    ]
