# Generated by Django 6.0.5 on 2026-05-26 20:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
        ("pregoes", "0004_propostainicialitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoGerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_contrato",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número do Contrato"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("previo", "Prévio"),
                            ("gerado", "Gerado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="gerado",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos_gerados",
                        to="cadastros.escola",
                        verbose_name="Escola",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos_gerados",
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos_gerados",
                        to="pregoes.pregao",
                        verbose_name="Pregão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato Gerado",
                "verbose_name_plural": "Contratos Gerados",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ContratoItemGerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marca",
                    models.CharField(blank=True, max_length=150, verbose_name="Marca"),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Unidade"
                    ),
                ),
                (
                    "quantidade_contratada",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Quantidade Contratada",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Unitário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor Total"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="documentos.contratogerado",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_contratados",
                        to="cadastros.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "quantitativo_escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_contratados",
                        to="pregoes.quantitativoescola",
                        verbose_name="Quantitativo da Escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Contrato Gerado",
                "verbose_name_plural": "Itens de Contratos Gerados",
                "ordering": ["item__nome_item"],
            },
        ),
    ]
