# Generated by Django 6.0.5 on 2026-06-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratogerado",
            name="data_distrato",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Distrato"
            ),
        ),
        migrations.AddField(
            model_name="contratogerado",
            name="motivo_distrato",
            field=models.TextField(blank=True, verbose_name="Motivo do Distrato"),
        ),
        migrations.AlterField(
            model_name="contratogerado",
            name="status",
            field=models.CharField(
                choices=[
                    ("previo", "Prévio"),
                    ("gerado", "Gerado"),
                    ("cancelado", "Cancelado"),
                    ("distratado", "Distratado"),
                ],
                default="gerado",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
