# Generated by Django 6.0.5 on 2026-06-03 12:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0002_contratogerado_data_distrato_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratogerado",
            name="status",
            field=models.CharField(
                choices=[
                    ("previo", "Prévio"),
                    ("gerado", "Gerado"),
                    ("cancelado", "Cancelado"),
                    ("distratado", "Distratado"),
                    ("parcialmente_distratado", "Parcialmente Distratado"),
                ],
                default="gerado",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="DistratoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_distrato", models.DateField(verbose_name="Data do Distrato")),
                (
                    "motivo_distrato",
                    models.TextField(verbose_name="Motivo do Distrato"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("total", "Total"), ("parcial", "Parcial")],
                        default="total",
                        max_length=20,
                        verbose_name="Tipo de Distrato",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Valor Total Distratado",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distratos",
                        to="documentos.contratogerado",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distrato de Contrato",
                "verbose_name_plural": "Distratos de Contratos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="DistratoContratoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_distratada",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Quantidade Distratada",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Unitário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor Total"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "contrato_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distratos",
                        to="documentos.contratoitemgerado",
                        verbose_name="Item do Contrato",
                    ),
                ),
                (
                    "distrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="documentos.distratocontrato",
                        verbose_name="Distrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Distrato",
                "verbose_name_plural": "Itens de Distrato",
                "ordering": ["contrato_item__item__nome_item"],
            },
        ),
    ]
