# Generated by Django 6.0.5 on 2026-06-03 13:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_alter_contratogerado_status_distratocontrato_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealinhamentoPreco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_realinhamento",
                    models.DateField(verbose_name="Data de Vigência do Realinhamento"),
                ),
                (
                    "justificativa",
                    models.TextField(verbose_name="Justificativa do Realinhamento"),
                ),
                (
                    "valor_total_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Valor Total Anterior",
                    ),
                ),
                (
                    "valor_total_novo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Valor Total Novo",
                    ),
                ),
                (
                    "diferenca_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Diferença Total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registrado", "Registrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="registrado",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="realinhamentos",
                        to="documentos.contratogerado",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Realinhamento de Preço",
                "verbose_name_plural": "Realinhamentos de Preços",
                "ordering": ["-data_realinhamento", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="RealinhamentoPrecoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_ativa",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Quantidade Ativa"
                    ),
                ),
                (
                    "valor_unitario_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Unitário Anterior",
                    ),
                ),
                (
                    "valor_unitario_novo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Unitário Novo",
                    ),
                ),
                (
                    "valor_total_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Valor Total Anterior",
                    ),
                ),
                (
                    "valor_total_novo",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor Total Novo"
                    ),
                ),
                (
                    "diferenca_valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Diferença de Valor",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "contrato_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="realinhamentos",
                        to="documentos.contratoitemgerado",
                        verbose_name="Item do Contrato",
                    ),
                ),
                (
                    "realinhamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="documentos.realinhamentopreco",
                        verbose_name="Realinhamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Realinhamento de Preço",
                "verbose_name_plural": "Itens de Realinhamento de Preço",
                "ordering": ["contrato_item__item__nome_item"],
            },
        ),
    ]
