# Generated by Django 6.0.5 on 2026-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0004_realinhamentopreco_realinhamentoprecoitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="realinhamentopreco",
            name="data_termo_aditivo",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Termo Aditivo"
            ),
        ),
        migrations.AddField(
            model_name="realinhamentopreco",
            name="numero_termo_aditivo",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Número do Termo Aditivo"
            ),
        ),
        migrations.AddField(
            model_name="realinhamentopreco",
            name="observacoes_termo_aditivo",
            field=models.TextField(
                blank=True, verbose_name="Observações do Termo Aditivo"
            ),
        ),
    ]
