# Generated by Django 6.0.5 on 2026-06-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_unidademedida_alter_item_unidade_medida"),
        ("documentos", "0005_realinhamentopreco_data_termo_aditivo_and_more"),
        ("pregoes", "0006_pregaoitem_media_preco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratogerado",
            name="ano_contrato",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Ano utilizado para reiniciar a numeração do contrato.",
                null=True,
                verbose_name="Ano do Contrato",
            ),
        ),
        migrations.AddField(
            model_name="contratogerado",
            name="numero_sequencial",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Sequencial anual do contrato dentro da escola.",
                null=True,
                verbose_name="Número Sequencial",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratogerado",
            constraint=models.UniqueConstraint(
                fields=("escola", "ano_contrato", "numero_sequencial"),
                name="unico_numero_contrato_por_escola_ano",
            ),
        ),
    ]
