# Generated by Django 6.0.5 on 2026-06-09 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0006_contratogerado_ano_contrato_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrocaMarca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_troca_marca",
                    models.DateField(verbose_name="Data de Vigência da Troca de Marca"),
                ),
                (
                    "justificativa",
                    models.TextField(verbose_name="Justificativa da Troca de Marca"),
                ),
                (
                    "numero_termo_aditivo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Número do Termo Aditivo",
                    ),
                ),
                (
                    "data_termo_aditivo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Termo Aditivo"
                    ),
                ),
                (
                    "observacoes_termo_aditivo",
                    models.TextField(
                        blank=True, verbose_name="Observações do Termo Aditivo"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registrado", "Registrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="registrado",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trocas_marca",
                        to="documentos.contratogerado",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Troca de Marca",
                "verbose_name_plural": "Trocas de Marca",
                "ordering": ["-data_troca_marca", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="TrocaMarcaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_ativa",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Quantidade Ativa"
                    ),
                ),
                (
                    "marca_anterior",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Marca Anterior"
                    ),
                ),
                (
                    "marca_nova",
                    models.CharField(max_length=150, verbose_name="Nova Marca"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "contrato_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trocas_marca",
                        to="documentos.contratoitemgerado",
                        verbose_name="Item do Contrato",
                    ),
                ),
                (
                    "troca_marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="documentos.trocamarca",
                        verbose_name="Troca de Marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Troca de Marca",
                "verbose_name_plural": "Itens de Troca de Marca",
                "ordering": ["contrato_item__item__nome_item"],
            },
        ),
    ]
