# Generated by Django 6.0.5 on 2026-07-28 20:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_alter_escola_cnpj_alter_fornecedor_cnpj"),
        ("documentos", "0007_trocamarca_trocamarcaitem"),
        ("pregoes", "0007_alter_pregao_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjetoVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_entrega",
                    models.DateField(verbose_name="Data de Entrega do Projeto"),
                ),
                (
                    "cronograma_entrega",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: semanal, quinzenal, mensal ou conforme solicitação da escola.",
                        max_length=255,
                        verbose_name="Cronograma de Entrega",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Total do Projeto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registrado", "Registrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="registrado",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projetos_venda",
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projetos_venda",
                        to="pregoes.pregao",
                        verbose_name="Chamada Pública",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projetos_venda_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto de Venda",
                "verbose_name_plural": "Projetos de Venda",
                "ordering": ["-data_entrega", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ProjetoVendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_ofertada",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Quantidade Ofertada",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Unitário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor Total"
                    ),
                ),
                (
                    "cronograma_entrega",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Cronograma de Entrega"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projetos_venda_itens",
                        to="cadastros.item",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "pregao_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projetos_venda_itens",
                        to="pregoes.pregaoitem",
                        verbose_name="Item da Chamada Pública",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="documentos.projetovenda",
                        verbose_name="Projeto de Venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Projeto de Venda",
                "verbose_name_plural": "Itens do Projeto de Venda",
                "ordering": ["pregao_item__ordem", "item__nome_item"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("projeto", "pregao_item"),
                        name="unique_item_por_projeto_venda",
                    )
                ],
            },
        ),
    ]
