# Generated by Django 6.0.5 on 2026-07-28 21:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_alter_escola_cnpj_alter_fornecedor_cnpj"),
        ("documentos", "0008_projetovenda_projetovendaitem"),
        ("pregoes", "0007_alter_pregao_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoChamadaPublicaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_adjudicada",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Quantidade Adjudicada",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Unitário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor Total"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registrado", "Registrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="registrado",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_chamada_publica",
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_chamada_publica",
                        to="cadastros.item",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "pregao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_chamada_publica",
                        to="pregoes.pregao",
                        verbose_name="Chamada Pública",
                    ),
                ),
                (
                    "pregao_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_chamada_publica",
                        to="pregoes.pregaoitem",
                        verbose_name="Item da Chamada Pública",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados",
                        to="documentos.projetovenda",
                        verbose_name="Projeto de Venda",
                    ),
                ),
                (
                    "projeto_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados",
                        to="documentos.projetovendaitem",
                        verbose_name="Item do Projeto de Venda",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_chamada_publica_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado da Chamada Pública",
                "verbose_name_plural": "Resultados da Chamada Pública",
                "ordering": ["pregao_item__ordem", "fornecedor__razao_social"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("projeto_item",),
                        name="unique_resultado_por_item_projeto_venda",
                    )
                ],
            },
        ),
    ]
