# Generated by Django 6.0.5 on 2026-07-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0009_resultadochamadapublicaitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="projetovendaitem",
            name="marca",
            field=models.CharField(
                blank=True,
                help_text="Marca ou descrição apresentada pelo fornecedor para o produto.",
                max_length=150,
                verbose_name="Marca / Descrição",
            ),
        ),
    ]
